apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-map
  namespace: ingress-map
  labels:
    app: ingress-map
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingress-map
  template:
    metadata:
      labels:
        app: ingress-map
    spec:
      serviceAccountName: ingress-map-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
      containers:
      - name: ingress-map
        image: virsuryaircas/ingress-map:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: FLASK_ENV
          value: "production"
        - name: FLASK_APP
          value: "app.py"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        envFrom:
        - secretRef:
            name: ingress-map-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
      restartPolicy: Always