apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-map

resources:
- namespace.yaml
- rbac.yaml
- secret.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- service-nodeport.yaml

labels:
- includeSelectors: true
  includeTemplates: true 
  pairs:
    app: ingress-map
    version: v1.0.0