apiVersion: v1
kind: Service
metadata:
  name: ingress-map-service
  namespace: ingress-map
  labels:
    app: ingress-map
spec:
  selector:
    app: ingress-map
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP