apiVersion: v1
kind: Service
metadata:
  name: ingress-map-nodeport
  namespace: ingress-map
  labels:
    app: ingress-map
spec:
  type: NodePort
  selector:
    app: ingress-map
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30050
    protocol: TCP